<?php
namespace App\Services;
use App\Models\{AiSummary,DailyReport,MissingDailyReport,PerformanceScore,Task,TaskApproval,Team,WorkProof};use App\Support\CurrentWorkspace;use Carbon\Carbon;use Illuminate\Database\Eloquent\Builder;
class ReportService{public function __construct(private CurrentWorkspace $cw){}private function wid():int{return $this->cw->required()->id;}private function tasks(array $f):Builder{return Task::with('assignedUsers')->where('workspace_id',$this->wid())->when($f['status']??null,fn($q,$v)=>$q->where('status',$v))->when($f['priority']??null,fn($q,$v)=>$q->where('priority',$v))->when($f['project_id']??null,fn($q,$v)=>$q->where('project_id',$v))->when($f['department_id']??null,fn($q,$v)=>$q->where('department_id',$v))->when($f['team_id']??null,fn($q,$v)=>$q->where('team_id',$v))->when($f['assignee_id']??null,fn($q,$v)=>$q->whereHas('assignees',fn($a)=>$a->where('user_id',$v)->where('workspace_id',$this->wid())))->when($f['from']??null,fn($q,$v)=>$q->whereDate('created_at','>=',$v))->when($f['to']??null,fn($q,$v)=>$q->whereDate('created_at','<=',$v));}
public function taskStatusReport(array $f){return $this->tasks($f)->latest()->paginate(50)->withQueryString();}
public function overdueTaskReport(array $f){return $this->tasks($f)->whereDate('due_date','<',today())->where('status','!=','completed')->orderBy('due_date')->paginate(50)->withQueryString();}
public function noUpdateTaskReport(array $f){$days=(int)($f['days']??7);$cut=now()->subDays(max(1,$days));return $this->tasks($f)->whereDoesntHave('activityLogs',fn($q)=>$q->where('created_at','>=',$cut))->whereDoesntHave('comments',fn($q)=>$q->where('created_at','>=',$cut))->where('updated_at','<',$cut)->paginate(50)->withQueryString();}
public function proofPendingReport(array $f){return $this->tasks($f)->where('proof_required',true)->where(fn($q)=>$q->whereDoesntHave('proofs')->orWhereHas('proofs',fn($p)=>$p->where('status','submitted')))->paginate(50)->withQueryString();}
public function approvalPendingReport(array $f){return TaskApproval::with('task','requester')->where('workspace_id',$this->wid())->where('status','pending')->latest()->paginate(50)->withQueryString();}
public function dailyReportSubmissionReport(array $f){return DailyReport::with('user')->where('workspace_id',$this->wid())->when($f['user_id']??null,fn($q,$v)=>$q->where('user_id',$v))->when($f['from']??null,fn($q,$v)=>$q->whereDate('report_date','>=',$v))->when($f['to']??null,fn($q,$v)=>$q->whereDate('report_date','<=',$v))->latest('report_date')->paginate(50)->withQueryString();}
public function missingReportReport(array $f){return MissingDailyReport::with('user')->where('workspace_id',$this->wid())->when($f['user_id']??null,fn($q,$v)=>$q->where('user_id',$v))->latest('report_date')->paginate(50)->withQueryString();}
public function employeePerformanceReport(array $f){return PerformanceScore::with('user')->where('workspace_id',$this->wid())->when($f['user_id']??null,fn($q,$v)=>$q->where('user_id',$v))->latest('score_date')->paginate(50)->withQueryString();}
public function teamPerformanceReport(array $f){return Team::where('workspace_id',$this->wid())->withCount(['tasks as assigned_tasks_count','tasks as completed_tasks_count'=>fn($q)=>$q->where('status','completed'),'tasks as overdue_tasks_count'=>fn($q)=>$q->whereDate('due_date','<',today())->where('status','!=','completed')])->paginate(50)->withQueryString();}
public function aiWeeklySummaryReport(array $f){return AiSummary::where('workspace_id',$this->wid())->where('summary_type','weekly_summary')->latest('generated_at')->paginate(50)->withQueryString();}
}
