<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
if(!Schema::hasTable('task_categories'))Schema::create('task_categories',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name');$t->text('description')->nullable();$t->string('color')->nullable();$t->boolean('proof_required')->default(false);$t->boolean('approval_required')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['workspace_id','is_active']);});
if(!Schema::hasTable('projects'))Schema::create('projects',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('code')->nullable();$t->text('description')->nullable();$t->string('client_name')->nullable();$t->foreignId('project_manager_id')->nullable()->constrained('users')->nullOnDelete();$t->string('status')->default('active');$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->timestamps();$t->softDeletes();$t->index(['workspace_id','status']);$t->index(['workspace_id','project_manager_id']);});
else Schema::table('projects',function(Blueprint $t){foreach(['code'=>'string','description'=>'text','client_name'=>'string','status'=>'string','start_date'=>'date','end_date'=>'date'] as $c=>$type)if(!Schema::hasColumn('projects',$c))$t->{$type}($c)->nullable();if(!Schema::hasColumn('projects','project_manager_id'))$t->foreignId('project_manager_id')->nullable()->constrained('users')->nullOnDelete();if(!Schema::hasColumn('projects','deleted_at'))$t->softDeletes();});
if(!Schema::hasTable('tasks'))Schema::create('tasks',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('task_number')->nullable();$t->string('title');$t->longText('description')->nullable();$t->foreignId('task_category_id')->nullable()->constrained('task_categories')->nullOnDelete();$t->foreignId('project_id')->nullable()->constrained('projects')->nullOnDelete();$t->foreignId('department_id')->nullable()->constrained('departments')->nullOnDelete();$t->foreignId('team_id')->nullable()->constrained('teams')->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->string('priority')->default('medium');$t->string('status')->default('new');$t->date('start_date')->nullable();$t->date('due_date')->nullable();$t->decimal('estimated_hours',8,2)->nullable();$t->timestamp('completed_at')->nullable();$t->foreignId('completed_by')->nullable()->constrained('users')->nullOnDelete();$t->boolean('proof_required')->default(false);$t->boolean('approval_required')->default(false);$t->string('approval_status')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['workspace_id','task_number']);$t->index(['workspace_id','status']);$t->index(['workspace_id','due_date']);$t->index(['workspace_id','priority']);$t->index(['workspace_id','project_id']);$t->index(['workspace_id','created_by']);});
if(!Schema::hasTable('task_assignees'))Schema::create('task_assignees',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('assigned_at')->nullable();$t->string('role')->default('assignee');$t->timestamps();$t->unique(['task_id','user_id']);$t->index(['workspace_id','user_id']);$t->index(['workspace_id','task_id']);});
if(!Schema::hasTable('task_watchers'))Schema::create('task_watchers',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['task_id','user_id']);});
if(!Schema::hasTable('task_checklists'))Schema::create('task_checklists',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->constrained()->cascadeOnDelete();$t->string('title');$t->boolean('is_completed')->default(false);$t->foreignId('completed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('completed_at')->nullable();$t->integer('sort_order')->default(0);$t->timestamps();$t->index(['workspace_id','task_id']);});
if(!Schema::hasTable('task_comments'))Schema::create('task_comments',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();$t->longText('comment');$t->foreignId('parent_id')->nullable()->constrained('task_comments')->nullOnDelete();$t->timestamps();$t->softDeletes();$t->index(['workspace_id','task_id']);$t->index(['workspace_id','user_id']);});
if(!Schema::hasTable('task_attachments'))Schema::create('task_attachments',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->constrained()->cascadeOnDelete();$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();$t->string('file_name');$t->string('original_name');$t->string('file_path');$t->string('file_disk')->default('local');$t->string('mime_type')->nullable();$t->unsignedBigInteger('file_size')->nullable();$t->string('attachment_type')->default('general');$t->timestamps();$t->index(['workspace_id','task_id']);$t->index(['workspace_id','uploaded_by']);});
if(!Schema::hasTable('task_activity_logs'))Schema::create('task_activity_logs',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('action');$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->text('description')->nullable();$t->timestamps();$t->index(['workspace_id','task_id']);$t->index(['workspace_id','action']);$t->index('created_at');});
}public function down():void{}};
