<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
if(!Schema::hasTable('workspaces'))Schema::create('workspaces',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('slug')->unique();$t->string('status')->default(config('workproof.defaults.workspace_status','trial'))->index();$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->string('edition')->default(config('workproof.edition','saas'));$t->string('timezone')->default(config('workproof.defaults.timezone','Asia/Dhaka'));$t->string('currency',3)->default(config('workproof.defaults.currency','BDT'));$t->date('trial_ends_at')->nullable();$t->timestamp('suspended_at')->nullable();$t->foreignId('suspended_by')->nullable()->constrained('users')->nullOnDelete();$t->text('suspension_reason')->nullable();$t->timestamps();$t->softDeletes();$t->index('slug');});
if(!Schema::hasTable('workspace_domains'))Schema::create('workspace_domains',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('domain')->unique();$t->string('type')->default('subdomain');$t->boolean('is_primary')->default(false);$t->boolean('is_verified')->default(false);$t->timestamps();$t->index(['workspace_id','is_primary']);});
if(!Schema::hasTable('workspace_settings'))Schema::create('workspace_settings',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->unique()->constrained()->cascadeOnDelete();$t->string('company_name')->nullable();$t->string('logo_path')->nullable();$t->string('timezone')->default(config('workproof.defaults.timezone','Asia/Dhaka'));$t->string('currency',3)->default(config('workproof.defaults.currency','BDT'));$t->json('working_days')->nullable();$t->time('office_start_time')->nullable();$t->time('office_end_time')->nullable();$t->time('daily_report_deadline')->nullable();$t->boolean('daily_report_required')->default(true);$t->boolean('proof_required_by_default')->default(false);$t->boolean('ai_enabled')->default(false);$t->json('notification_settings')->nullable();$t->json('feature_flags')->nullable();$t->timestamps();});
if(!Schema::hasTable('workspace_user'))Schema::create('workspace_user',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('role_key')->nullable();$t->string('status')->default('active');$t->foreignId('invited_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('joined_at')->nullable();$t->timestamps();$t->unique(['workspace_id','user_id']);$t->index(['workspace_id','status']);$t->index('user_id');});
if(!Schema::hasTable('departments'))Schema::create('departments',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name');$t->foreignId('parent_id')->nullable()->constrained('departments')->nullOnDelete();$t->foreignId('head_user_id')->nullable()->constrained('users')->nullOnDelete();$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['workspace_id','is_active']);});
if(!Schema::hasTable('teams'))Schema::create('teams',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('department_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->foreignId('team_lead_id')->nullable()->constrained('users')->nullOnDelete();$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['workspace_id','department_id']);});
if(!Schema::hasTable('plans'))Schema::create('plans',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->decimal('monthly_price',12,2)->default(0);$t->decimal('yearly_price',12,2)->nullable();$t->string('currency',3)->default('USD');$t->integer('user_limit')->nullable();$t->integer('project_limit')->nullable();$t->integer('storage_limit_mb')->nullable();$t->integer('ai_monthly_quota')->nullable();$t->boolean('is_public')->default(true);$t->boolean('is_active')->default(true);$t->timestamps();});
if(!Schema::hasTable('plan_features'))Schema::create('plan_features',function(Blueprint $t){$t->id();$t->foreignId('plan_id')->constrained()->cascadeOnDelete();$t->string('feature_key');$t->string('feature_name');$t->string('value')->nullable();$t->boolean('enabled')->default(true);$t->timestamps();$t->unique(['plan_id','feature_key']);});
if(!Schema::hasTable('subscriptions'))Schema::create('subscriptions',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('plan_id')->nullable()->constrained()->nullOnDelete();$t->string('status')->default('trial');$t->date('trial_ends_at')->nullable();$t->date('current_period_start')->nullable();$t->date('current_period_end')->nullable();$t->string('billing_cycle')->nullable();$t->timestamps();$t->index(['workspace_id','status']);});
if(!Schema::hasTable('audit_logs'))Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('actor_type')->nullable();$t->string('action');$t->string('subject_type')->nullable();$t->unsignedBigInteger('subject_id')->nullable();$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->string('ip_address')->nullable();$t->string('user_agent')->nullable();$t->timestamps();$t->index(['workspace_id','action']);$t->index(['subject_type','subject_id']);$t->index('created_at');});
if(!Schema::hasTable('workspace_onboarding_steps'))Schema::create('workspace_onboarding_steps',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('step_key');$t->boolean('is_completed')->default(false);$t->timestamp('completed_at')->nullable();$t->foreignId('completed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['workspace_id','step_key']);});
}public function down():void{}};
