<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::table('subscriptions',function(Blueprint $t){if(!Schema::hasColumn('subscriptions','grace_ends_at'))$t->date('grace_ends_at')->nullable()->after('current_period_end');if(!Schema::hasColumn('subscriptions','gateway'))$t->string('gateway')->default('manual')->after('billing_cycle');if(!Schema::hasColumn('subscriptions','metadata'))$t->json('metadata')->nullable()->after('gateway');});
Schema::create('invoices',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('subscription_id')->nullable()->constrained()->nullOnDelete();$t->string('invoice_number')->unique();$t->string('status')->default('draft');$t->string('currency',3)->default('USD');$t->decimal('subtotal',12,2)->default(0);$t->decimal('discount_total',12,2)->default(0);$t->decimal('tax_total',12,2)->default(0);$t->decimal('total',12,2)->default(0);$t->decimal('amount_paid',12,2)->default(0);$t->decimal('amount_due',12,2)->default(0);$t->date('issue_date')->nullable();$t->date('due_date')->nullable();$t->timestamp('paid_at')->nullable();$t->text('notes')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['workspace_id','status']);$t->index('due_date');$t->index('invoice_number');});
Schema::create('invoice_items',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('invoice_id')->constrained()->cascadeOnDelete();$t->string('description');$t->decimal('quantity',10,2)->default(1);$t->decimal('unit_price',12,2)->default(0);$t->decimal('total',12,2)->default(0);$t->json('metadata')->nullable();$t->timestamps();});
Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('invoice_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('subscription_id')->nullable()->constrained()->nullOnDelete();$t->string('payment_number')->unique();$t->string('gateway')->default('manual');$t->string('status')->default('pending');$t->string('currency',3)->default('USD');$t->decimal('amount',12,2);$t->string('transaction_reference')->nullable();$t->timestamp('paid_at')->nullable();$t->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete();$t->text('verification_note')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['workspace_id','status']);$t->index('gateway');$t->index('transaction_reference');});
Schema::create('payment_methods',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->nullable()->constrained()->cascadeOnDelete();$t->string('gateway');$t->string('display_name');$t->json('config')->nullable();$t->boolean('is_active')->default(false);$t->boolean('is_default')->default(false);$t->timestamps();});
Schema::create('feature_usage_logs',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('feature_key');$t->integer('usage_count')->default(0);$t->date('usage_date');$t->json('metadata')->nullable();$t->timestamps();$t->unique(['workspace_id','feature_key','usage_date']);$t->index(['workspace_id','feature_key']);});
Schema::create('storage_usage_logs',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->decimal('used_mb',12,2)->default(0);$t->timestamp('calculated_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
}public function down():void{foreach(['storage_usage_logs','feature_usage_logs','payment_methods','payments','invoice_items','invoices'] as $table)Schema::dropIfExists($table);}};
