<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
if(!Schema::hasTable('daily_reports'))Schema::create('daily_reports',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->date('report_date');$t->string('status')->default('draft');$t->longText('completed_summary')->nullable();$t->longText('in_progress_summary')->nullable();$t->longText('pending_summary')->nullable();$t->longText('blocker_summary')->nullable();$t->longText('tomorrow_plan')->nullable();$t->timestamp('submitted_at')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->text('review_comment')->nullable();$t->integer('quality_score')->nullable();$t->boolean('is_late')->default(false);$t->timestamps();$t->softDeletes();$t->unique(['workspace_id','user_id','report_date']);$t->index(['workspace_id','report_date']);$t->index(['workspace_id','user_id','report_date']);$t->index(['workspace_id','status']);});
if(!Schema::hasTable('daily_report_items'))Schema::create('daily_report_items',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('daily_report_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->nullable()->constrained('tasks')->nullOnDelete();$t->string('item_type')->default('completed');$t->string('title');$t->longText('description')->nullable();$t->integer('time_spent_minutes')->nullable();$t->integer('sort_order')->default(0);$t->timestamps();$t->index(['workspace_id','daily_report_id']);$t->index(['workspace_id','task_id']);});
if(!Schema::hasTable('work_proofs'))Schema::create('work_proofs',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->constrained()->cascadeOnDelete();$t->foreignId('daily_report_id')->nullable()->constrained('daily_reports')->nullOnDelete();$t->foreignId('submitted_by')->nullable()->constrained('users')->nullOnDelete();$t->string('proof_type')->default('file');$t->string('title')->nullable();$t->longText('note')->nullable();$t->string('url')->nullable();$t->string('file_path')->nullable();$t->string('file_disk')->default('local');$t->string('original_name')->nullable();$t->string('mime_type')->nullable();$t->unsignedBigInteger('file_size')->nullable();$t->string('status')->default('submitted');$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->text('rejection_reason')->nullable();$t->timestamps();$t->index(['workspace_id','task_id']);$t->index(['workspace_id','submitted_by']);$t->index(['workspace_id','status']);});
if(!Schema::hasTable('task_approvals'))Schema::create('task_approvals',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->constrained()->cascadeOnDelete();$t->foreignId('requested_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('approver_id')->nullable()->constrained('users')->nullOnDelete();$t->string('status')->default('pending');$t->timestamp('requested_at')->nullable();$t->timestamp('reviewed_at')->nullable();$t->text('comment')->nullable();$t->text('rejection_reason')->nullable();$t->timestamps();$t->index(['workspace_id','task_id']);$t->index(['workspace_id','approver_id']);$t->index(['workspace_id','status']);});
if(!Schema::hasTable('missing_daily_reports'))Schema::create('missing_daily_reports',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->date('report_date');$t->timestamp('expected_deadline')->nullable();$t->string('status')->default('missing');$t->timestamp('marked_at')->nullable();$t->timestamp('resolved_at')->nullable();$t->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();$t->text('note')->nullable();$t->timestamps();$t->unique(['workspace_id','user_id','report_date']);$t->index(['workspace_id','report_date']);$t->index(['workspace_id','user_id']);$t->index(['workspace_id','status']);});
if(!Schema::hasTable('manager_feedbacks'))Schema::create('manager_feedbacks',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('given_by')->nullable()->constrained('users')->nullOnDelete();$t->string('subject_type')->nullable();$t->unsignedBigInteger('subject_id')->nullable();$t->longText('feedback');$t->string('feedback_type')->default('general');$t->timestamps();});
}public function down():void{}};
